# Fase 1 Definición del problema y entorno reproducible

**Asignatura:** MCDI500 Programación para la Ciencia de Datos  
**Evaluación:** Sumativa 1  
**Grupo:** 5  
**Integrantes:** Marco Álvarez Araya, María Fassler Neumann y Ricardo Jaramillo Pulgar

## 1 Propósito del notebook

## 2 Contextualización del Proyecto

El proyecto aborda el análisis de los permisos activos de uso de calles en la ciudad de San Francisco, utilizando el conjunto de datos público disponible a través de DataSF. El conjunto de datos contiene información asociada a permisos de uso del espacio
público, el cual permite analizar características relacionadas con el tipo de permiso, su ubicación territorial y otros atributos disponibles. El análisis busca identificar patrones y factores asociados con la duración de estos permisos, mediante técnicas de exploración, procesamiento y análisis de datos.

## 3 Definición de la Problemática

El uso temporal de los espacios públicos mediante permisos de uso de calles
genera registros con distintas características, tipos de permisos, ubicaciones y
duraciones.

No obstante, la existencia de múltiples atributos en el conjunto de datos dificulta
identificar qué características presentan una mayor asociación con la duración de
los permisos activos.

Por esa razón, se plantea analizar el conjunto de datos con el propósito de
identificar patrones y asociaciones entre la duración de los permisos y sus
principales características.


## 4 Pregunta de Investigación
**¿Qué factores se asocian con la duración de los permisos activos de uso de calles
en San Francisco, considerando el tipo de permiso, la ubicación territorial y las
demás características disponibles en el conjunto de datos?**

## 5. Objetivo general
Analizar los factores asociados a la duración de los permisos activos de uso de
calles en San Francisco, mediante técnicas de exploración, procesamiento y análisis
de datos, considerando el tipo de permiso, la ubicación territorial y las demás
características disponibles en el conjunto de datos.

## 6. Objetivos específicos
1. Caracterizar los permisos activos de uso de calles según sus principales
   atributos, incluyendo tipo, ubicación y duración.

2. Explorar y depurar el conjunto de datos, identificando valores faltantes,
   registros duplicados, inconsistencias y posibles valores atípicos.

3. Analizar la asociación entre la duración de los permisos y variables como
   el tipo de permiso, la ubicación territorial y otras características
   relevantes disponibles en el conjunto de datos.

4. Identificar patrones y diferencias en la duración de los permisos mediante
   técnicas de análisis y visualización de datos.

## 7. Alcance del Proyecto
El proyecto se enfocará en el análisis de los permisos activos de uso de calles
contenidos en el conjunto de datos seleccionado.

El análisis considerará las variables disponibles en la fuente de datos que
resulten pertinentes para estudiar la duración de los permisos, incluyendo
características relacionadas con su tipo, ubicación y temporalidad.

El proyecto contempla las etapas de obtención, exploración, limpieza,
transformación, validación y análisis de los datos.

No se buscará establecer relaciones causales entre las variables, sino identificar
asociaciones y patrones presentes en los datos.

## 8. Limitaciones del Proyecto
El proyecto puede presenta algunas limitaciones que deben ser consideradas al momento de interpretar los resultados obtenidos.

- Datos faltantes o inconsistentes: durante las etapas de exploración y preparación podrían identificarse valores faltantes, duplicados, inconsistencias o registros que requieran tratamiento. Estas situaciones pueden limitar el uso de determinadas variables o afectar los análisis posteriores.

- Dependencia de la fuente de datos: el análisis estará limitado a la información disponible en el conjunto de datos público de DataSF. Por lo tanto, las conclusiones dependerán de las variables registradas y de la calidad de la información proporcionada por la fuente.

- Variables disponibles: el estudio solo podrá considerar factores que estén registrados en el conjunto de datos. Pueden existir características relevantes para la duración de los permisos que no estén disponibles o no puedan ser incorporadas al análisis.

Estas limitaciones serán consideradas durante las etapas de preparación, análisis e interpretación de los resultados, asegurando que las conclusiones sean coherentes con la información disponible y con el alcance definido para el proyecto.

## 9 Supuestos del Análisis
Para el desarrollo del análisis se consideran los siguientes supuestos:

- Los registros disponibles representan permisos activos según la definición
  establecida por la fuente de datos.

- Las fechas y demás variables temporales disponibles permiten determinar o
  estimar la duración de los permisos.

- Las variables de ubicación disponibles permiten realizar un análisis territorial
  de los permisos.

- Los datos pueden contener valores faltantes, inconsistencias o valores atípicos,
  los cuales serán identificados y tratados durante la etapa de procesamiento.

- Las conclusiones estarán limitadas a la información contenida en el conjunto
  de datos y al período representado por este.

## 10 Fuente y descripción del conjunto de datos
El conjunto seleccionado corresponde a Active Street-Use Permits, publicado a través del portal de datos abiertos DataSF, administrado por la City and Conty of San Francisco. Para efectos de reproducibilidad y como fuente de datos, el proyecto utilizaa una copia descargada el 9 de septiembre de 2026, denominada Active_Street-Use_Permits_20260909.csv.

### 10.1 Fuente, enlace y licencia

|Elemento|Descripción|
|---|---|
| Conjunto de datos | Active Street-Use Permits |
| Fuente | DataSF |
| Institución responsable | City and County of San Francisco |
| Recurso | x8nh-xzn6 |
| Archivo de trabajo | Active_Street-Use_Permits_20260909.csv |
| Fecha de descarga | 9 de septiembre de 2026 |
| Licencia | PDDL 1.0 |

### 10.2 Justificación de la selección del dataset

## 11 Validación inicial del conjunto de datos

## 12 Reconomimiento inicial y diccionario preliminar de variables

## 13 Entorno de trabajo reproducible

### 13.1 Versión de Python y Kernel utlizado

### 13.2 Librerías y dependencias

## 14 Estructura del repositorio y uso de rutas relativas

## 15 Módulo reutilizable inicial

## 16 Control de versiones y colaboración en Github

## 17 Verificación final de la fase 1

## 3 Diagnóstico Inicial de Completitud de Datos
Se revisará la presencia de valores faltantes en el conjunto de datos original. En este punto, se descibirá la calidad inicial de la información, sin modificar ni eliminar registros durante la Fase 1.

In [11]:
from pathlib import Path
import pandas as pd

ruta_proyecto = Path.cwd().parents[1]

ruta_datos = ruta_proyecto / "data" / "raw" / "Active_Street-Use_Permits_20260909.csv"

df = pd.read_csv(ruta_datos)

df.head()

,permit_number,streetname,Cross Street 1,Cross Street 2,Permit Type,Agent,AgentPhone,Permit Purpose,Approved Date,Status,...,Y,Latitude,Longitude,bpa,Location,the_geom,analysis_neighborhood,supervisor_district,data_as_of,data_loaded_at
0,26EXC-01641,08TH ST,NATOMA ST,HOWARD ST,Excavation,Ronan Construction Inc.,415-779-5262,"8th St, Clay St and Leavenworth St - Pavement ...",04/15/2026,APPROVED,...,"2110825,76329","37,77644115815","-122,4118820325",NaN,POINT (-122.41188203249555 37.77644115815177),POINT (-122.411882032 37.776441158),South of Market,6.0,2026/04/16 03:34:45 AM,2026/04/17 05:23:32 AM
1,25EXC-01889,SAN BRUNO AVE,MANSELL ST \ SALINAS AVE,ORDWAY ST,Excavation,"Cratus, Inc.",(415)939-2840,WD-2876 8-Inch Ductile Iron Water Main Repl...,07/18/2025,ACTIVE,...,"2090569,998","37,7209782871","-122,40087332838",NaN,POINT (-122.40087332838284 37.720978287099676),POINT (-122.400873328 37.720978287),Portola,10.0,2025/09/10 05:11:34 AM,2025/09/12 05:08:57 AM
2,23IE-00344,WALNUT ST,PACIFIC AVE,JACKSON ST,StrtImprov,"Partner's Contracting, Inc.",415-492-9233,Remove and reconstruct sidewalk and existing (...,08/26/2025,APPROVED,...,"2116443,35732","37,79125689282","-122,44945871865",202210184608,POINT (-122.44945871865453 37.79125689282032),POINT (-122.449458719 37.791256893),Presidio Heights,2.0,2025/08/28 03:42:52 AM,2025/08/29 05:13:53 AM
3,25EXC-01889,CAMPBELL AVE,SAN BRUNO AVE,BRUSSELS ST,Excavation,"Cratus, Inc.",(415)939-2840,WD-2876 8-Inch Ductile Iron Water Main Repl...,07/18/2025,ACTIVE,...,"2088480,85453","37,71525239967","-122,40007624052",NaN,POINT (-122.40007624051567 37.715252399671314),POINT (-122.400076241 37.7152524),Visitacion Valley,10.0,2025/09/10 05:11:34 AM,2025/09/12 05:08:57 AM
4,25EXC-01889,CANDLESTICK COVE WAY,EXECUTIVE PARK BLVD,NaN,Excavation,"Cratus, Inc.",(415)939-2840,WD-2876 8-Inch Ductile Iron Water Main Repl...,07/18/2025,ACTIVE,...,"2087023,572266","37,71134702909","-122,39401110729",NaN,POINT (-122.39401110729395 37.71134702909027),POINT (-122.394011107 37.711347029),Bayview Hunters Point,10.0,2025/09/10 05:11:34 AM,2025/09/12 05:08:57 AM

In [10]:
df.shape

(6852, 29)

In [12]:
proporcion_nulos = df.isna().mean()
proporcion_nulos

permit_number            0.000000
streetname               0.000000
Cross Street 1           0.000000
Cross Street 2           0.145943
Permit Type              0.000000
Agent                    0.001313
AgentPhone               0.015908
Permit Purpose           0.249854
Approved Date            0.002627
Status                   0.000000
cnn                      0.000000
permit_zipcode           0.000000
permit_start_date        0.121862
permit_end_date          0.103765
permit_address           0.630619
24/7 Contact             0.029480
Inspector                0.365587
CurbRampWork             0.964390
X                        0.001168
Y                        0.001168
Latitude                 0.000000
Longitude                0.000000
bpa                      0.956655
Location                 0.000000
the_geom                 0.000000
analysis_neighborhood    0.000438
supervisor_district      0.000292
data_as_of               0.000000
data_loaded_at           0.000000
dtype: float64

In [13]:
porcentaje_nulos = proporcion_nulos * 100
porcentaje_nulos_ordenado = porcentaje_nulos.sort_values(ascending=False)
porcentaje_nulos_ordenado

CurbRampWork             96.438996
bpa                      95.665499
permit_address           63.061880
Inspector                36.558669
Permit Purpose           24.985406
Cross Street 2           14.594279
permit_start_date        12.186223
permit_end_date          10.376532
24/7 Contact              2.948044
AgentPhone                1.590776
Approved Date             0.262697
Agent                     0.131349
Y                         0.116754
X                         0.116754
analysis_neighborhood     0.043783
supervisor_district       0.029189
Status                    0.000000
permit_number             0.000000
streetname                0.000000
Cross Street 1            0.000000
Permit Type               0.000000
permit_zipcode            0.000000
cnn                       0.000000
Latitude                  0.000000
Longitude                 0.000000
the_geom                  0.000000
Location                  0.000000
data_as_of                0.000000
data_loaded_at            0.000000
dtype: float64

In [16]:
tabla_nulos = porcentaje_nulos_ordenado.reset_index()
tabla_nulos.columns = ["Variable", "Porcentaje de nulos"]
tabla_nulos["Porcentaje de nulos"] = tabla_nulos["Porcentaje de nulos"].round(2)
tabla_nulos = tabla_nulos[
    tabla_nulos["Porcentaje de nulos"]>0
    ]
tabla_nulos

                 Variable  Porcentaje de nulos
0            CurbRampWork                96.44
1                     bpa                95.67
2          permit_address                63.06
3               Inspector                36.56
4          Permit Purpose                24.99
5          Cross Street 2                14.59
6       permit_start_date                12.19
7         permit_end_date                10.38
8            24/7 Contact                 2.95
9              AgentPhone                 1.59
10          Approved Date                 0.26
11                  Agent                 0.13
12                      Y                 0.12
13                      X                 0.12
14  analysis_neighborhood                 0.04
15    supervisor_district                 0.03